name: Lint CLI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install dependencies (including dev dependencies)
        working-directory: cli/
        env:
          BROWNIE_LIB: 1
        run: pip install -e ".[dev]"
      - name: Black syntax check
        working-directory: cli/
        run: black --check wing
